### ISSUE TITLE
Naming of services

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#117]
We should rename some services (e.g. webinterface & python_program)

**Comment by wp99cp** [comment]
I would propose the following names for the services:

- [ ] `frontend` instead of `webinterface`
- [ ] `backend` instead of `python_program`
- [ ] `routing_engine` instead of `route_engine`
- [ ] `mapfish_print_server` instead of `pdf_map_export`
- [x] `docs` for `docs`
- [x] `swiss_TLM_api` for `swiss_TLM_api`

**Comment by maede97** [comment]
Sounds good!

**Comment by wp99cp** [comment]
We should also rethink the names of the runtime environments...

May be something like `local-dev` instead of `live`?


See [comment in #121](https://github.com/cevi/automatic_walk-time_tables/pull/121#issuecomment-1306624657).
