### ISSUE TITLE
Adding too many points by hand results in broken xlsx.

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#179]
When adding many points by hand, the xlsx file contains too many newlines. The excel form breaks. We should limit the number of points.

**Comment by carlobeltrame** [comment]
We also ran into this problem, on a 30Lkm hike in a course. Our course participants reported that there was some kind of warning about a maximum of 21 points, and they were surprised that it still worked (and then at first didn't notice that the Excel was broken). The problem was fixable in this case by redoing the whole process and choosing fewer points.

**Comment by wp99cp** [comment]
Is fixed in the export step, but the frontend still allows to create to-many way points, this results in a crash during the final export. #147

**Comment by wp99cp** [comment]
should be addressed with https://github.com/cevi/automatic_walk-time_tables/blob/aab7e3717e8933f3a41ed2e1b9fbb497313a920e/backend/automatic_walk_time_tables/path_transformers/douglas_peucker_transformer.py#L76-L77

as introduced by https://github.com/cevi/automatic_walk-time_tables/commit/aab7e3717e8933f3a41ed2e1b9fbb497313a920e

**Comment by maede97** [comment]
Confirm, is fixed now.
