### ISSUE TITLE
MZB can not be generated when using converted kml file

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/automatic_walk-time_tables#51]
Route made on map.geo.admin.ch
Downloaded kml file
converted with kml2gpx.com

On map.cevi.tools, background image is generated correctly, MZB not.
kml file: https://www.dropbox.com/s/gns4z0rqw72zbxd/map.geo.admin.ch_KML_20220129090654.kml?dl=0

**Comment by maede97** [comment]
@ThomasHaefliger what settings did you use when converting your kml file?

**Comment by ThomasHaefliger** [comment]
@maede97 Waypoints & Tracks

**Comment by maede97** [comment]
I have quickly looked into the generated GPX file.
The generated one from kmp2gpx.com seems to have another structure (other field names). We need to investigate this further and try to find a solution.
@wp99cp Any idea on what we should do?

**Comment by maede97** [comment]
One idea would be, to add support for KML files as well?

**Comment by wp99cp** [comment]
I took your KML file, converted it according to your settings and then looked at the server logs. It seems, the problem is not the structure of the generated GPX file, which is within the specs and can therefore be read by the application without any problems. But rather the missing elevation information. All heights in your GPX file are set to zero. 

This leads to a math exception in the following line. Where the value of the log is not defined. https://github.com/cevi/automatic_walk-time_tables/blob/16518c8ac52d18795ee267fe1fc0eded7776e6c4/python_program/automatic_walk_time_tables/walk_time_table/walk_table.py#L40 

This is because the KML file that you can export from map.geo.admin.ch is missing the elevation data. If you take a look at the specifications of a KML file, you will see that the height information is an optional field. Therefore, we will unfortunately not be able to support KML files in our application.

**Comment by wp99cp** [comment]
I'll keep this issue open for the moment, as we should investigate an option to use map.geo.admin.ch as a data source. 

In the meantime @ThomasHaefliger I suggest using the SwisstopoApp on a tablet or mobile phone, or the SchweizMobile web app.

**Comment by wp99cp** [comment]
> We should add an entry in the webpage stating why exported KML files from map.geo.admin.ch do not work.

Good idea! Can be combined with #41.

**Comment by wp99cp** [comment]
We need to look at this API Endpoint: https://api3.geo.admin.ch/rest/services/profile.json.
Documentation: https://api3.geo.admin.ch/services/sdiservices.html?highlight=profile#profile

**Comment by maede97** [comment]
@ThomasHaefliger stay tuned, KML files are supported with the next release!

**Comment by ThomasHaefliger** [comment]
@maede97 whooop whooop 👍
